spring.profiles.active=${SPRING_PROFILES_ACTIVE}

spring.application.name=bffwebapp

server.port=${PORT}

# security
security.jwt.issuer=easycv-bff-web-app
security.jwt.access.key=${JWT_ACCESS_KEY}
security.jwt.refresh.key=${JWT_REFRESH_KEY}
security.jwt.access-expiration-seconds=1800
security.jwt.refresh-expiration-minutes=5000

# docs
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api/bff-web-app/docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/api/bff-web-app/docs/swagger-ui.html
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=false
springdoc.swagger-ui.syntaxHighlight.activated=true

# Logger
commons.log-endpoint.enabled=true

# Properties for user-api
user-api.endpoint.baseurl=http://localhost:8081/api/users
user-api.endpoint.get-user-by-id=/{userId}
user-api.endpoint.patch=/{userId}
user-api.endpoint.get-user-light-by-credential=/auth/login
user-api.endpoint.get-user-light-by-id=/auth/{userId}/refresh
user-api.endpoint.reset-password=/auth/reset


# Properties for curriculum
curriculum-api.endpoint.baseurl=http://localhost:8083
curriculum-api.endpoint.get-all=/api/curriculums
curriculum-api.endpoint.get-by-id=/api/curriculums/{curriculumId}
curriculum-api.endpoint.post=/api/curriculums
curriculum-api.endpoint.put=/api/curriculums/{curriculumId}
curriculum-api.endpoint.delete=/api/curriculums/{curriculumId}

# Properties for domain-api
domain-api.endpoint.baseurl=http://localhost:8082
domain-api.endpoint.get-all=/api/domains
domain-api.endpoint.get-by-id=/api/domains/{domainId}
domain-api.endpoint.post=/api/domains
domain-api.endpoint.put=/api/domains/{domainId}
domain-api.endpoint.delete=/api/domains/{domainId}

# cors
cors.enable=true
allowed-cors-origin=http://localhost:4200